
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-conf
  namespace: dynatrace
  labels:
    app: fluentd
    component: fluentd-conf
data:
  CLUSTER_ID: "a1d81911-b6bf-4f47-874a-41da3fecbc7e"
  AG_INGEST_URL: "https://fluentd-activegate:9999/e/bix24852/api/v2/logs/ingest"
  fluent.conf: |-
    # Ingest logs from nodes
    <match fluent.**>
      @type null
    </match>

    <source>
      @type tail
      path /var/log/containers/*nginx*.log
      pos_file /var/log/fluentd.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag nginx
      <parse>
        @type nginx
        key_name log
        reserve_data yes
        expression  /^(?<logtime>\S+)\s+(?<logtype>\S+)\s+(?<type>\w+)\s+(?<ip>\S+)\s+\[(?<time_local>[^\]]*)\]\s+(?<method>\S+)\s+(?<request>\S+)\s+(?<httpversion>\S*)\s+(?<status>\S*)\s+(?<bytes_sent>\S*)\s+(?<responsetime>\S*)\s+(?<proxy>\S*)\s+(?<upstream_responsetime>\S*)\s+(?<ressourcename>\S*)\s+(?<upstream_status>\S*)\s+(?<ingress_name>\S*)\s+(?<ressource_type>\S*)\s+(?<ressource_namesapce>\S*)\s+(?<service>\w*)/
        types ip:string,time_local:string,method:string,request:string,httpversion:string,status:integer,bytes_sent:integer,responsetime:float,request_time:float,proxy:string,upstream_responsetime:float,ressourcename:string,ressource_type:string,ressource_namesapce:string,service:string
        time_format %d/%b/%Y:%H:%M:%S %z
      </parse>
      read_from_head true
      keep_time_key true
    </source>
    <source>
       @type prometheus
       bind 0.0.0.0
       port 9914
       metrics_path /metrics
    </source>

    <filter  nginx>
      @type prometheus
      <labels>
        method ${method}
        request ${request}
        status ${status}
        ingressnamespace ${ressource_namesapce}
        targetservice ${service}
        ressourcename ${ressourcename}
      </labels>
      <metric>
        name ingress_response_time
        type gauge
        desc responset time
        key responsetime
      </metric>
      <metric>
        name ingress_byte_sent
        type gauge
        desc byte sent
        key bytes_sent
      </metric>
      <metric>
        name ingress_requests
        type counter
        desc The total number of request
      </metric>
      <metric>
        name ingress_status
        type counter
        desc status code
        key status
      </metric>
    </filter>

    <filter nginx>
      @type grep
        <exclude>
        key service
        pattern /^$/
        # or, to exclude all messages that are empty or include only white-space:
        </exclude>
    </filter>

    <match nginx>
        @type  stdout
    </match>
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: dynatrace
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        app: fluentd-pipeline
        version: v1
    spec:
      serviceAccountName: dynatrace-monitoring
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      initContainers:
      - name: fluentd-permission-fix
        image: busybox
        command: [ "sh","-c","touch /var/log/fluentd.pos; chmod -R 777 /var/log/fluentd.pos; " ]
        volumeMounts:
          - name: var-log
            mountPath: /var/log/
      containers:
      - name: fluentd
        image: hrexed/fluentd_dynatrace_prometheus:0.1
        ports:
          - containerPort: 9914
            name: fluentdprom
            protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 400Mi
            ephemeral-storage: 10Gi
          requests:
            cpu: 100m
            memory: 200Mi
            ephemeral-storage: 10Gi
        env:
          - name: FLUENT_UID
            value: "0"
          - name: CLUSTER_ID
            valueFrom:
              configMapKeyRef:
                name: fluentd-conf
                key: CLUSTER_ID
          - name: AG_INGEST_URL
            valueFrom:
              configMapKeyRef:
                name: fluentd-conf
                key: AG_INGEST_URL
          - name: LOG_INGEST_TOKEN
            valueFrom:
              secretKeyRef:
                name: tokens
                key: log-ingest
        volumeMounts:
          - name: var-log
            mountPath: /var/log
            readOnly: true
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: var-log-pos
            mountPath: /var/log/fluentd.pos
          - mountPath: /fluentd/etc/fluent.conf
            name: data
            subPath: fluent.conf
            readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: var-log
          hostPath:
            path: /var/log/
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: var-log-pos
          hostPath:
            path: /var/log/fluentd.pos
            type: FileOrCreate
        - name: data
          configMap:
            name: fluentd-conf


