apiVersion: v1
kind: Namespace
metadata:
  name: dynatrace
  labels:
    name: dynatrace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynatrace-monitoring
  namespace: dynatrace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynatrace-monitoring-cluster
rules:
  - apiGroups:
      - ""
      - batch
      - apps
      - apps.openshift.io
    resources:
      - nodes
      - pods
      - services
      - namespaces
      - deployments
      - replicasets
      - deploymentconfigs
      - replicationcontrollers
      - jobs
      - cronjobs
      - statefulsets
      - daemonsets
      - events
      - resourcequotas
      - pods/proxy
    verbs:
      - list
      - watch
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynatrace-monitoring-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dynatrace-monitoring-cluster
subjects:
  - kind: ServiceAccount
    name: dynatrace-monitoring
    namespace: dynatrace