apiVersion: v1
kind: Service
metadata:
  labels:
    app: ngninx-exporter
  name: nginx-prom-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/scheme: 'http'
    prometheus.io/port: '9113'
    prometheus.io/path: '/metrics'
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9113
      targetPort: metrics
      protocol: TCP
  selector:
    app: ngninx-nginx-ingress
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-servicemon
  labels:
    release: prometheus
spec:
  endpoints:
    - interval: 10s
      port: metrics
  selector:
    matchLabels:
      app: ngninx-exporter