apiVersion: v1
kind: Service
metadata:
  labels:
    app: fluentd-exporter
  name: fluentd-prom-metrics
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/scheme: 'http'
    prometheus.io/port: '9914'
    prometheus.io/path: '/metrics'
    metrics.dynatrace.com/port: '9914'
    metrics.dynatrace.com/scrape: 'true'
    metrics.dynatrace.com/path: '/metrics'
spec:
  ports:
    - port: 9914
      name: fluentdprom
      targetPort: fluentdprom
      protocol: TCP
  selector:
    app: fluentd-pipeline
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fluentd-servicemon
  labels:
    app: fluentd-pipeline
    release: prometheus
spec:
  endpoints:
    - interval: 5s
      port: fluentdprom
  selector:
    matchLabels:
      app: fluentd-exporter